"""Assemble the three videos.

Scenes are generated by re-simulating, not by replaying stored footage: the
brains and the world are deterministic given their seeds, so a run can be
reproduced exactly and drawn frame by frame.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from flybrain.connectome import build as build_connectome
from flybrain.network import Population
from minesim.world import MILESTONES, N_MILESTONES, MineSim
from render import chart, layouts, ui
from render.video import Subtitles, VideoWriter

OUT = Path(__file__).resolve().parent.parent / "out"
FPS = 30

# A storyboard sets this so every scene logs its captions to the same SRT.
ACTIVE_SUBS: Subtitles | None = None


@dataclass
class Format:
    name: str
    size: tuple[int, int]
    hero: callable
    population: callable
    caption_box: tuple[int, int, int, int]
    caption_size: int
    grid: tuple[int, int]


LANDSCAPE = Format("youtube", layouts.LANDSCAPE, layouts.hero_landscape,
                   layouts.population_landscape, (40, 130, 1000, 1076), 30, (11, 7))
PORTRAIT = Format("portrait", layouts.PORTRAIT, layouts.hero_portrait,
                  layouts.population_portrait, (60, 210, 1020, 1168), 34, (7, 10))


# --------------------------------------------------------------------- pieces
def caption_at(captions, t: int) -> str:
    for start, end, text in captions:
        if start <= t < end:
            return text
    return ""


def hero_scene(writer: VideoWriter, fmt: Format, genome: np.ndarray, world_seed: int,
               agent: int, ticks: int, n_agents: int, captions=(), stride: int = 1,
               title: str = "", sub: str = "", brain_seed: int = 0,
               hold_end: float = 0.0, hud_label: str = "SPEEDRUN TIMER",
               start_tick: int = 0, subs: Subtitles | None = None,
               repeat: int = 1) -> int:
    """Render one agent's run.  `stride` skips ticks to compress long runs."""
    conn = build_connectome()
    env = MineSim(n_agents, seed=world_seed, max_ticks=ticks)
    brain = Population(conn, n_agents, obs_dim=MineSim.OBS_DIM, seed=brain_seed)
    brain.reset()
    brain.set_genomes(np.repeat(genome[None, :], n_agents, axis=0))
    env.reset(seed=world_seed)

    subs = subs or ACTIVE_SUBS
    written = 0
    frame = None
    for t in range(ticks):
        actions = np.argmax(brain.step(env.observe(), env.bearing()), axis=0)
        _, done = env.step(actions)
        if t < start_tick or t % stride:
            if done.all():
                break
            continue
        rates = {k: float(v[agent]) for k, v in brain.population_rates().items()}
        kc = brain.r[brain.sl_kc][:, agent]
        frame = fmt.hero(env, rates, kc, float(brain.g[:, agent].mean()), agent,
                         title or "FLY BRAIN PLAYS MINECRAFT",
                         ui.format_time(int(env.tick[agent])), sub,
                         hud_label=hud_label,
                         hud_sub=f"stage {env.stage()[agent] + 1}/{N_MILESTONES}  ·  "
                                 f"{MILESTONES[min(env.stage()[agent], N_MILESTONES - 1)].replace('_', ' ')}")
        text = caption_at(captions, t)
        frame = ui.caption_over(frame, fmt.caption_box, text, fmt.caption_size)
        if subs is not None:
            subs.mark(writer.count, text)
        writer.write(frame, repeat)
        written += repeat
        if done.all() or env.won[agent]:
            break
    if frame is not None and hold_end:
        writer.write(frame, int(hold_end * FPS))
        written += int(hold_end * FPS)
    return written


def scripted_scene(writer: VideoWriter, fmt: Format, world_seed: int, ticks: int,
                   n_agents: int = 8, agent: int = 0, captions=(), stride: int = 1,
                   title: str = "RUTA DE REFERENCIA", sub: str = "",
                   subs: Subtitles | None = None) -> None:
    """The hand-written speedrunner, for comparison."""
    from minesim import scripted
    subs = subs or ACTIVE_SUBS
    env = MineSim(n_agents, seed=world_seed, max_ticks=ticks)
    env.reset(seed=world_seed)
    flat = {k: 0.0 for k in ("VPN", "KC", "MBON", "DAN", "CX", "DN")}
    kc = np.zeros(1, np.float32)
    for t in range(ticks):
        _, done = env.step(scripted.act(env))
        if t % stride:
            continue
        frame = fmt.hero(env, flat, kc, 1.0, agent, title,
                         ui.format_time(int(env.tick[agent])), sub,
                         hud_label="REFERENCE RUN",
                         hud_sub=f"stage {env.stage()[agent] + 1}/{N_MILESTONES}  ·  "
                                 f"{MILESTONES[min(env.stage()[agent], N_MILESTONES - 1)].replace('_', ' ')}")
        text = caption_at(captions, t)
        frame = ui.caption_over(frame, fmt.caption_box, text, fmt.caption_size)
        if subs is not None:
            subs.mark(writer.count, text)
        writer.write(frame)
        if done.all() or env.won[agent]:
            break


def population_scene(writer: VideoWriter, fmt: Format, genomes: np.ndarray,
                     world_seed: int, ticks: int, title: str, sub: str,
                     right: str, captions=(), stride: int = 2,
                     brain_seed: int = 0, subs: Subtitles | None = None) -> None:
    conn = build_connectome()
    n = genomes.shape[0]
    env = MineSim(n, seed=world_seed, max_ticks=ticks)
    brain = Population(conn, n, obs_dim=MineSim.OBS_DIM, seed=brain_seed)
    brain.reset()
    brain.set_genomes(genomes)
    env.reset(seed=world_seed)
    subs = subs or ACTIVE_SUBS
    cols, rows = fmt.grid
    for t in range(ticks):
        actions = np.argmax(brain.step(env.observe(), env.bearing()), axis=0)
        _, done = env.step(actions)
        if t % stride:
            continue
        prog = env.progress()
        best = MILESTONES[min(int(prog.max()), N_MILESTONES - 1)]
        stats = [f"best      {best.replace('_', ' ')}",
                 f"mean      {prog.mean():4.2f} milestones",
                 f"alive     {int(env.alive.sum())}/{n}",
                 f"completed {int(env.won.sum())}",
                 "",
                 f"clock     {ui.format_time(int(env.tick.max()))}"]
        frame = fmt.population(env, title, right, sub, cols=cols, rows=rows, stats=stats)
        text = caption_at(captions, t)
        frame = ui.caption_over(frame, (0, 0, fmt.size[0], fmt.size[1] - 8), text,
                                fmt.caption_size)
        if subs is not None:
            subs.mark(writer.count, text)
        writer.write(frame)
        if done.all():
            break


def chart_scene(writer: VideoWriter, fmt: Format, history: list[dict],
                seconds: float, hold: float = 1.5) -> None:
    n = len(history)
    frames = int(seconds * FPS)
    for i in range(frames):
        upto = max(1, int(n * (i + 1) / frames))
        writer.write(chart.learning_curve(history, upto, fmt.size, total_gens=n))
    writer.write(chart.learning_curve(history, n, fmt.size, total_gens=n),
                 int(hold * FPS))


def card(writer: VideoWriter, fmt: Format, lines, seconds: float, foot: str = "",
         align: str = "center") -> None:
    writer.write(layouts.title_card(fmt.size, lines, align=align, foot=foot),
                 int(seconds * FPS))


def still_scene(writer: VideoWriter, fmt: Format, frame: np.ndarray,
                captions: list[tuple[float, str]],
                subs: Subtitles | None = None) -> None:
    """Hold one image while a sequence of captions plays over it."""
    subs = subs or ACTIVE_SUBS
    W, H = fmt.size
    box = (0, 0, W, H - 24)
    for seconds, text in captions:
        n = int(seconds * FPS)
        if subs is not None:
            for k in range(n):
                subs.mark(writer.count + k, text)
        writer.write(ui.caption_over(frame, box, text, fmt.caption_size), n)


def connectome_frame(fmt: Format) -> np.ndarray:
    return chart.connectome_portrait(build_connectome(), fmt.size)


def load_run(path: Path = OUT / "evolution.json") -> dict:
    return json.loads(Path(path).read_text())
